### ISSUE TITLE
Shader fails to load with error

### ISSUE THREAD

**Issue by Azagwen** [Septonious/Solas-Shader#37]
This shader fails to load into Iris 1.7.3+mc1.21
```
net.irisshaders.iris.gl.shader.ShaderCompileException: composite3.fsh: composite3.fsh: 0(235) : error C1503: undefined variable "calculateMovement"
0(237) : error C1503: undefined variable "getFireflyNoise"

	at net.irisshaders.iris.gl.shader.GlShader.createShader(GlShader.java:46)
	at net.irisshaders.iris.gl.shader.GlShader.<init>(GlShader.java:25)
	at net.irisshaders.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:88)
	at net.irisshaders.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49)
	at net.irisshaders.iris.pipeline.CompositeRenderer.createProgram(CompositeRenderer.java:326)
	at net.irisshaders.iris.pipeline.CompositeRenderer.<init>(CompositeRenderer.java:123)
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.<init>(IrisRenderingPipeline.java:322)
	at net.irisshaders.iris.Iris.createPipeline(Iris.java:578)
	at net.irisshaders.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:33)
	at net.irisshaders.iris.Iris.reload(Iris.java:529)
	at net.irisshaders.iris.Iris.handleKeybinds(Iris.java:144)
	at net.minecraft.class_310.handler$bgo002$iris$onTick(class_310.java:11173)
	at net.minecraft.class_310.method_1574(class_310.java:2012)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by Septonious** [comment]
will investigate soon
